elifesciences/elife-flux-cluster

- deployments/reviewer/libero-reviewer--prod.yaml
- deployments/reviewer/libero-reviewer--stg.yaml
@erkannt not sure if this is the correct way to do this but currently the value `libero-reviewer--prod-client-canary.prod` is breaking the browser test run as the url redirect is not taking us back to reviewer-staging correctly. Trying this as at least a temp fix to get pipeline green.
> use absolute baseurl instead of one without protocol prefix

- system/flux/flux.yaml
Some context, the fluxcd automation is currently failing as it is hitting dockers pull rate limit. The correct solution would be to update to flux v2 which has changed the behaviour for checking for new images, but obviously that is quite some work and not something I really want to action now.
Looking at the chart for flux 1.10.2, I can see there are some config options to increase the interval used to check for new images in the registry, as such it seems that increasing this from the default 5 minutes to 1h should hopefully bring us under the 100 image pulls in a 6 hour window and get things working again.
> fix: increase automation interval to work around pull rate limits

- deployments/data-hub/data-hub--stg.yaml
The value for CPU usage for the web pod is completely incorrect and too high (probably a copy paste from another resource request). 
This change should free more scheduling resources for the rest of the deploy. Also tweak the postgres values which are default, but very high vs actual usage.
> fix(data-hub): tweak incorrect data-hub CPU request values to allow better scheduling

- deployments/data-hub/data-hub--stg.yaml
The Airflow scheduler seems to use a lot of CPU when idle. This sets a CPU limit to prevent resource exhaustion of other services on the node.
> fix(data-hub): add a CPU limit to scheduler

- deployments/data-hub/data-hub--stg.yaml
Could be the cause of high airflow scheduler CPU as it loops continuously looking for changes to the DAG python files. 
Set to 5 mins, though @de-code suggests if it could be disabled that would be fine too
Refs elifesciences/data-hub-issues#330
> fix(data-hub): reconfigure airflow schedulers interval between parsing files in an attempt to reduce idle CPU usage.

- deployments/data-hub/data-hub--stg.yaml
increase the AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL value again to be 60 seconds in an attempt to reduce scheduler CPU again.
It's managed to climb backup and cause CPU throttling messages again
> fix(data-hub): increase the AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL

- deployments/data-hub/data-hub--stg.yaml
We only have one static user, so this process is just chugging resources.
> fix(data-hub): remove sync of users

- deployments/data-hub/data-hub--stg.yaml
Airflow has its own authentication mechanism, but we actually rely on the cluster OAuth proxy to allow elife staff to access it.
This change should instruct airflow to allow all "guest" (i.e. unauthenticated within airflow) visits to act as administrators, and disables internal authentication as a result. All visits still need to pass the OAuth proxy first, so this is OK.
notes: Lines 248-253 are from the default `webserver_config.py` as deployed by the airflow helm chart.
> feature(data-hub): Turn off Airflow internal authentication

- deployments/data-hub/data-hub--prod.yaml
- deployments/data-hub/data-hub--stg.yaml
Due to a bug in airflow, we're undoing the changes to authentication until we can update to airflow > 2.0.1
> fix(data-hub): reactivate authentication

- system/infra/ingress-nginx-controller.yaml
First step towards https://github.com/elifesciences/issues/issues/7226 is to remove the nginx-controller image pinning on the prod server. 
I've checked history of [elife-flux-test](https://github.com/elifesciences/elife-flux-test) and [elife-flux-cluster](https://github.com/elifesciences/elife-flux-cluster) and there doesn't appear to be a reason for it, just that the image pinning was removed in `flux-test` just after the files were copied to `flux-prod`.
This change will get prod and test on the same version and same image, for testing purposes.
> Remove nginx-controller image pinning

- system/monitoring/alertrules-misc.yaml
Data-hub worker is expected to fairly regularly spike to use ~1.7 CPUs over an extended period of time.
Here we're moving the alert to fire above 1.8, as that would be exceptional load over an hour.
> fix(prometheus): change alert rules to only fix elevated CPU above 1.8

- deployments/data-hub/data-hub-configs.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/384
We should allow creation of the FTP directory, because we are using the test FTP server in staging.
> enable ftp create directory in staging

- deployments/data-hub/test-ftpserver/deployment.yaml
- deployments/data-hub/test-ftpserver/services.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/384
The data transfer failed.
Extending the port range will hopefully fix that.
Port ranges as per: https://github.com/delfer/docker-alpine-ftp-server
> extend test ftp port range for data transfer

- deployments/data-hub/data-hub-configs.yaml
With 10 days, there still seem to be quite a few records in view and sometimes it seems to get stuck.
Reducing it to 1 day would "lock-in" the progress made more frequently.
Only downside is that from the original start date, it might have to go over a few days without any data.
(But those requests should still be relatively quick in comparison)
> reduce the number of days to request in a single batch to one

- deployments/data-hub/data-hub--prod.yaml
- deployments/data-hub/data-hub--stg.yaml
To stop the flapping that we sometimes see depending on which node it is deployed to, give Data hub deployments most of a node in terms of CPU resources. This should stop kubernetes deploying the data-hub with other CPU intensive, or too numerous other deployments
> fix(data-hub): request more CPU space for data-hubs

- deployments/data-hub/release-data-hub--prod.yaml
- deployments/data-hub/release-data-hub--stg.yaml
related to https://github.com/elifesciences/data-hub-core-airflow-dags/pull/961
Tested the pipeline manually, in both staging and prod.
This enables the schedule to run daily.
> added semantic scholar pipeline schedule interval

- deployments/data-hub/release-data-hub--stg.yaml
```log
File "/home/airflow/.local/bin/airflow", line 5, in <module>
from airflow.__main__ import main
File "/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py", line 35, in <module>
from airflow import settings
File "/home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py", line 35, in <module>
from airflow.configuration import AIRFLOW_HOME, WEBSERVER_CONFIG, conf  # NOQA F401
File "/home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py", line 1345, in <module>
conf.validate()
File "/home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py", line 293, in validate
self._validate_config_dependencies()
File "/home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py", line 387, …
```
> added AIRFLOW__DATABASE__SQL_ALCHEMY_CONN_CMD

- deployments/data-hub/release-data-hub--stg.yaml
```
airflow command error: argument GROUP_OR_COMMAND: `airflow checkdb` command, has been removed, please use `airflow db check`, see help above.
```
https://github.com/airflow-helm/charts/blob/main/charts/airflow/values.yaml
> removed legacyCommands section

- deployments/data-hub/release-data-hub--stg.yaml
```
File "/home/airflow/.local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
worker.init_process()
File "/home/airflow/.local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
self.load_wsgi()
File "/home/airflow/.local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
self.wsgi = self.app.wsgi()
File "/home/airflow/.local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
self.callable = self.load()
File "/home/airflow/.local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
return self.load_wsgiapp()
File "/home/airflow/.local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
return …
```
> added AIRFLOW__SENTRY__BEFORE_SEND: ""

- kustomizations/apps/data-hub-configs/semantic-scholar.config.yaml
see https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1007
related to https://github.com/elifesciences/data-hub-issues/issues/432
picked 23, as 24 with a 24h schedule could cause it to delay to 48h by chance.
I have backfilled the `provenance.doi` for both `staging` and `prod`.
> wait at least 23h before retrying 404s for semantic scholar

- kustomizations/apps/data-hub-configs/semantic-scholar.config.yaml
related to https://github.com/elifesciences/data-hub-issues/issues/432
The articles that we are currently mostly interested in for Sciety are from bioRxiv and medRxiv.
So adding this filter will reduce the number of articles retrieved significantly.
(In Sciety saved articles from other preprint servers, if any, would still be included)
> only retrieve biorxiv and medrxiv articles from semantic scholar

- kustomizations/apps/data-hub-configs/semantic-scholar.config.yaml
related to https://github.com/elifesciences/data-hub-issues/issues/436
Now that we have the API Key configured, we should be able to retrieve more documents.
> re-enable all preprint servers for semantic scholar pipeline

- kustomizations/apps/data-hub-configs/semantic-scholar.config.yaml
There are quite a few articles receiving 404 from Semantic Scholar that are unlikely getting resolved within a day.
In particular Research Square has more than 28k such articles.
This change will retry those articles after 30 days (instead of every day).
bioRxiv and medRxiv should still be retried daily. (There are currently less than 600 articles with 404)
> reduce Semantic Scholar 404 retry for other preprint servers

- deployments/data-hub/release-data-hub--prod.yaml
- deployments/data-hub/release-data-hub--stg.yaml
- deployments/data-hub/release-data-hub--test.yaml
Observed some automated releases have been failing. Plus, we're relying on the autoscaler for deployments now, and new nodes take a few minutes to be active anyway.
> fix(data-hub): increase helm release timeout from 5m to 10m

- kustomizations/apps/data-hub-configs/semantic-scholar-recommendation.config.yaml
Biophysics Colab would like to get the recommendations updated even if they do not save new articles.
Adding the date to the "list_key" should achieve that.
(We currently don't need that for prev events used for evaluation)
> update current semantic scholar recommendations daily

- deployments/data-hub/release-data-hub--stg.yaml
Updated airflow configuration variable names as they are deprecated with the new airflow version
https://github.com/elifesciences/data-hub-issues/issues/442
> [data-hub staging] Update airflow config

- deployments/data-hub/release-data-hub--prod.yaml
- deployments/data-hub/release-data-hub--test.yaml
Updated airflow configuration variable names as they are deprecated with the new airflow version
https://github.com/elifesciences/data-hub-issues/issues/442
> [data-hub prod] Update airflow config

- kustomizations/apps/data-hub-configs/crossref-event-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/553
Added cold spring habour doi prefix (biorxiv/medrxiv) to crossref event data pipeline config
There will be quite a few records. Hopefully it will be able to retrieve them before updating the state.
The data will be useful for Sciety, to see for example what users tweet bioRxiv articles.
> enabled biorxiv/medrxiv for crossref event data

- kustomizations/apps/data-hub-configs/crossref-event-data-pipeline.config.yaml
- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/553
As I can't customise the URL for one prefix only, I added it as a separate Web API config.
I added the `until-collected-date` parameter to the URL to limit the response. The date will need to be updated later to retrieve all of the data.
I configured `crossref_event_data_web_api` as the output table in case the schema is different by using the Web API (without telling it a separate schema like we do for the CrossRef Event Data pipeline)
> CrossRef Event Data via Web API

- deployments/data-hub/data-hub-api/data-hub-api--prod.yaml
- deployments/data-hub/data-hub-api/data-hub-api--stg.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/556
Used the wrong secret name (as I had copied it from peerscout)
> fixed data-hub-api gcloud secret name

- deployments/data-hub/sciety-discovery/automations/sciety-discovery-stable-policy.yaml
- deployments/data-hub/sciety-discovery/automations/sciety-discovery-stable-source.yaml
- deployments/data-hub/sciety-discovery/automations/sciety-discovery-unstable-policy.yaml
- deployments/data-hub/sciety-discovery/automations/sciety-discovery-unstable-source.yaml
- deployments/data-hub/sciety-discovery/sciety-discovery--prod.yaml
- deployments/data-hub/sciety-discovery/sciety-discovery--stg.yaml
Deploy sciety discovery to elife cluster for now,
Under the `data-hub` namespace to have access to the GCP credentials.
This may move to the Sciety cluster in the future.
> deploy sciety discovery

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/577
Configuring the schema enables the functionality that checks timestamps and sets them to None if they are not valid (according to `dateparser`)
> configure CrossRef Event Data schema for Web API pipeline

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
google.api_core.exceptions.Forbidden: 403 Quota exceeded
```log
[2023-01-12, 12:42:46 UTC] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.biorxiv.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
warnings.warn(
[2023-01-12, 12:42:49 UTC] {generate_schema.py:218} INFO - Processed 26 lines
[2023-01-12, 12:42:51 UTC] {taskinstance.py:1851} ERROR - Task failed with exception
File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
return_value = self.execute_callable()
File …
```
> [Data Hub config] Increase day period for bioRxiv and medRxiv apis config

- kustomizations/apps/data-hub-configs/ejp-xml-data-pipeline--test.config.yaml
- kustomizations/apps/data-hub-configs/ejp-xml-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/491
eJPXmlObjectKeyPattern: 'ejp_e*' # having all XML files from legacy and new side (ejp_eLife* and ejp_elife-rp*)
> Updated eJPXmlObjectKeyPattern to include XML files from new site 

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
This will record searches for bioRxiv/medRxiv and Sciety (might extend it to other preprint servers in the near future).
This depends on the following PR to be merged and deployed:
https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1198
> Data Hub, Web API: Twitter Search for bioRxiv/medRxiv and Sciety

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
I noticed this in the Airflow logs:
```log
AIRFLOW_CTX_DAG_RUN_ID=trig__2023-02-16T02:44:01.937240+00:00_biorxiv_medrxiv_meca_path_metadata_13
[2023-02-16, 06:29:56 UTC] {taskinstance.py:1851} ERROR - Task failed with exception
File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 175, in execute
return_value = self.execute_callable()
File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 193, in execute_callable
return self.python_callable(*self.op_args, **self.op_kwargs)
File "/opt/airflow/dags/dags/web_api_data_import_pipeline.py", line 39, in web_api_data_etl
data_config = WebApiConfig.from_dict(data_config_dict, deployment_env=dep_env)
File …
```
> Web API: Fix remove second incomplete biorxiv_medrxiv_meca_path_metadata config

- deployments/data-hub/sciety-labs/sciety-labs--prod.yaml
- deployments/data-hub/sciety-labs/sciety-labs--stg.yaml
It is now using more memory since including group lists.
(Staging is currently crash looping)
> Increase memory requirements for Sciety Labs

- deployments/epp/prod/epp-kustomization.yaml
This will increase the resilience of EPP during rollouts and cluster failures
> Increase the number of EPP-server instances to 3

- deployments/data-hub/release-data-hub--stg.yaml
- deployments/data-hub/release-data-hub--test.yaml
related to https://github.com/elifesciences/data-hub-issues/issues/483
Using a post-render after chart has been rendered, we can patch the statefulset to add a liveness probe checking if the connections are active. failure will restart the pod.
At time of writing, we had a hung worker in data-hub prod (as per the linked ticket). This is the result of running the script in each worker's container:
```
> kubectl exec -it -n data-hub data-hub--stg-worker-0 -- sh
Defaulted container "airflow-worker" out of: airflow-worker, log-cleanup, check-db (init), wait-for-db-migrations (init)
(airflow)CONNECTION_CHECK_MAX_COUNT=0 exec /entrypoint python -m celery --app airflow.executors.celery_executor.app inspect ping -d celery@$(hostname)
->  celery@data-hub--stg-worker-0: OK
pong
1 node online.
> …
```
> fix(data-hub): patch the stateful set to add a liveness probe that verifies there are connections active

- deployments/data-hub/sciety-labs/sciety-labs--prod.yaml
- deployments/data-hub/sciety-labs/sciety-labs--stg.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/644
We are using the same ids in production and staging
> Sciety Labs: Configure Cookiebot and GTM

- system/kube-system/descheduler/release.yaml
relates to https://github.com/elifesciences/issues/issues/8216
> deploy(system/kube-system/descheduler): force registry change to overcome deprecated registry

- deployments/data-hub/release-data-hub--prod.yaml
- deployments/data-hub/release-data-hub--stg.yaml
- deployments/data-hub/release-data-hub--test.yaml
The liveness probe for airflow web in the test env is failing, The logs don't show us enough information to know how long to delay startup for:
```
[2023-04-11 08:27:28 +0000] [48] [INFO] Starting gunicorn 20.1.0
[2023-04-11 08:27:37,970] {providers_manager.py:208} INFO - Optional provider feature disabled when importing 'airflow.providers.google.leveldb.hooks.leveldb.LevelDBHook' from 'apache-airflow-providers-google' package
/home/airflow/.local/lib/python3.8/site-packages/azure/storage/common/_connection.py:82 SyntaxWarning: "is" with a literal. Did you mean "=="?
[2023-04-11 08:27:43 +0000] [48] [INFO] Listening at: http://0.0.0.0:8080 (48)
[2023-04-11 08:27:43 +0000] [48] [INFO] Using worker: sync
[2023-04-11 08:27:43 +0000] [80] [INFO] Booting worker with pid: 80
[2023-04-11 …
```
> fix(data-hub/test): add an initial delay to liveness probe to overcome early restarts

- deployments/data-hub/release-data-hub--prod.yaml
Because of Git Hub rate limit we need to import xml data partially every 90 min.
> Update Schedule Interval for Article XML Pipeline for initial load 

- kustomizations/apps/data-hub-configs/europepmc-labslink--test.config.yaml
- kustomizations/apps/data-hub-configs/europepmc-labslink.config.yaml
- kustomizations/apps/data-hub-configs/semantic-scholar-recommendation.config.yaml
- kustomizations/apps/data-hub-configs/semantic-scholar.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/752
Since the view is now deployed via our BigQuery Views project we can use the env related dataset (e.g. `prod`)
Then switched to `normalized_event_name` but also included `EvaluationPublicationRecorded`.
That way we can switch `normalized_event_name` to the more recent event name (`EvaluationPublicationRecorded`)
> Sciety: Add support for new evaluation events

- deployments/data-hub/sciety-labs/sciety-labs--prod.yaml
- deployments/data-hub/sciety-labs/sciety-labs--stg.yaml
Currently Sciety Labs is sometimes in a restart loop because it takes too long to load the data.
This increases the timeout.
(Once we are using OpenSearch, this could reduce the data it needs to load at startup)
> Sciety Labs: Increase readiness timeout

- kustomizations/apps/data-hub-configs/bigquery-to-opensearch--stg.yaml
In development we reduced the batch size to 100 for quicker feedback.
But in production this is meant to be increased again (unless we are experiencing timeouts).
> OpenSearch: Increased batch size to 1000

- deployments/data-hub/sciety-labs/sciety-labs--prod.yaml
The hope is that this will make it more likely that at least one instance is available.
Higher availability is desired as there is a dependency on the RSS feeds, a link from Sciety and Sciety might soon use the API provided by Sciety Labs.
> Sciety Labs: Increase replicas to 2 in production

- kustomizations/apps/data-hub-configs/bigquery-to-opensearch--stg.yaml
Because the DOI is the id, it is a required field. There are currently 28 papers without a DOI.
> OpenSearch: Exclude S2 papers without DOI

- kustomizations/apps/data-hub-configs/bigquery-to-opensearch--stg.yaml
Getting:
```text
[2023-08-23T10:08:41.468+0000] {base.py:259} WARNING - POST https://opensearch-staging:9200/_bulk [status:N/A request:10.076s]
File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
six.raise_from(e, None)
File "<string>", line 3, in raise_from
File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 461, in _make_request
httplib_response = conn.getresponse()
File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
response.begin()
File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
version, status, reason = self._read_status()
File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
line = …
```
> OpenSearch: Reduce batch size to 500 due to timeout

- kustomizations/apps/data-hub-configs/bigquery-to-opensearch--stg.yaml
Still experiencing timeouts. So reducing it back to 100.
> OpenSearch: Reducing batch size back to 100 due to timeout

- kustomizations/apps/data-hub-configs/bigquery-to-opensearch--prod.yaml
- kustomizations/apps/data-hub-configs/bigquery-to-opensearch--stg.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/763
The `timeout` is now configurable (and has a higher default value).
> OpenSearch: Increased batch size and timeout

- deployments/data-hub/sciety-labs/sciety-labs--prod.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/765
This could get merged after the OpenSearch pipeline completed it's import.
The following URL should provide related articles: `https://labs.sciety.org/articles/by?article_doi=10.1101/2022.10.04.510840` at the bottom.
> Sciety Labs: Use OpenSearch prod instance

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/771
requires https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1281
This should retrieve the all of the evaluated articles from EuropePMC.
We only need the DOI really (but the WebAPI doesn't seem to support a field selector yet).
> Web API: Retrieve evaluated article from EuropePMC

- deployments/data-hub/data-hub-api/data-hub-api--prod.yaml
Added replica to increase the availability of the DocMaps API.
> Add replica for data-hub-api in prod

- deployments/basex-validator/prod/basex-validator-kustomization.yaml
- deployments/basex-validator/prod/namespace.yaml
- deployments/basex-validator/prod/updateautomation.yaml
- kustomizations/apps/basex-validator/automations/basex-validator-policy.yaml
- kustomizations/apps/basex-validator/automations/basex-validator-source.yaml
- kustomizations/apps/basex-validator/deployment.yaml
- kustomizations/apps/basex-validator/ingress.yaml
- kustomizations/apps/basex-validator/kustomization.yaml
- kustomizations/apps/basex-validator/service.yaml
This allows us to better control the resources without having to maintain the helm chart
> move basex-validator from helm chart to kustomization

- deployments/peerscout/peerscout--prod.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/780
> PeerScout API: Applied Sciety Labs timeouts to PeerScout, except timeoutSeconds

- kustomizations/apps/data-hub-configs/bigquery-to-opensearch--stg.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/791
depends on https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1299 (otherwise it would replace documents)
This configures the Sciety Data pipeline
> OpenSearch: Configure Sciety Data (staging)

- kustomizations/apps/data-hub-configs/bigquery-to-opensearch--prod.yaml
part of elifesciences/data-hub-issues#791
depends on elifesciences/data-hub-core-airflow-dags#1299 (otherwise it would replace documents)
This configures the Sciety Data pipeline for prod. (See #2402 for staging equivalent)
> OpenSearch: Configure Sciety Data (prod)

- kustomizations/apps/data-hub-configs/bigquery-to-opensearch--stg.yaml
I realised I will also benefit from the title for those preprints that are not in the S2 data.
Although not yet sure how to handle it. Maybe use the EuropePMC title more.
Then also added other metadata.
It seems the OpenSearch update is taking about the same time, independent of the number of fields.
> OpenSearch: Import more EuropePMC metadata

- kustomizations/apps/data-hub-configs/bigquery-to-opensearch--stg.yaml
depends on https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1312 (for support of key paths for timestamp)
This reverts #2427 and #2438
Instead a new index `preprints_v2` is populated with the following top-level fields:
- doi
- s2
- europepmc
- sciety
> OpenSearch: Separate S2, EuropePMC and Sciety fields in `preprints_v2` (staging)

- kustomizations/apps/data-hub-configs/bigquery-to-opensearch--stg.yaml
follow-up for #2443
The query didn't exclude NULL dois (mostly in S2, only one in EuropePMC)
> Opensearch fix preprints s2 null doi

- deployments/data-hub/release-data-hub--prod.yaml
- deployments/data-hub/release-data-hub--stg.yaml
- deployments/data-hub/release-data-hub--test.yaml
part of elifesciences/data-hub-issues#785
Follow-up on 2437
This should make the logs available in the Airflow UI, in the "traditional" view.
In #2437 the mount was incorrectly added to the `scheduler` instead of `web`
This PR fixes that by moving the mount to `web`
> Data Hub: Fix Airflow Logs not shown in UI, move mount to `web`

- deployments/data-hub/sciety-labs/sciety-labs--prod.yaml
- deployments/data-hub/sciety-labs/sciety-labs--stg.yaml
for https://github.com/sciety/sciety-labs/pull/239
The deprecated environment variables can be removed after the code change is deployed.
> Sciety Labs: Configure OpenSearch preprints_v2

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/798
Follow-up fix for #2472
> Web API: Fixed exclude query pointing to wrong table name

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of elifesciences/data-hub-issues#798
Follow-up fix for #2472
The query did not return any results because the sub query contained NULL DOIs.
> Web API: S2 Embeddings, fixed include query

- kustomizations/apps/data-hub-configs/bigquery-to-opensearch--stg.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/798
This is loading the embeddings from the new Web API into OpenSearch
(initially for staging only)
> OpenSearch: Load S2 Embeddings from model-apis (Staging)

- kustomizations/apps/data-hub-configs/bigquery-to-opensearch--prod.yaml
part of elifesciences/data-hub-issues#798
same as #2475 but for prod
This is loading the embeddings from the new Web API into OpenSearch
I made [code changes to Sciety Labs to not make it fail without the S2 metadata](https://github.com/sciety/sciety-labs/pull/259).
> OpenSearch: Load S2 Embeddings from model-apis (Prod)

- deployments/data-hub/release-data-hub--stg.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/810
After the following change:
https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1338
We are seeing:
```text
Broken DAG: [/opt/airflow/dags/dags/web_api_data_import_pipeline.py] Traceback (most recent call last):
File "/opt/airflow/git_repos/core_dag/data_pipeline/utils/pipeline_config.py", line 269, in get_pipeline_config_for_env_name_and_config_parser
get_yaml_file_as_dict(conf_file_path),
File "/opt/airflow/git_repos/core_dag/data_pipeline/utils/pipeline_file_io.py", line 45, in get_yaml_file_as_dict
with open(file_location, 'r', encoding='UTF-8') as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: '/dag_config_files/web-api-data-pipeline.config.yaml'
```
In development, we now mount it to …
> Data Hub: Mount config to scheduler (staging)

- deployments/data-hub/release-data-hub--prod.yaml
- deployments/data-hub/release-data-hub--test.yaml
part of elifesciences/data-hub-issues#810
After the following change:
elifesciences/data-hub-core-airflow-dags#1338
Same as #2487 but applying to prod and test
> Data Hub: Mount config to scheduler (prod and test)

- kustomizations/apps/data-hub-configs/semantic-scholar-recommendation.config.yaml
- kustomizations/apps/data-hub-configs/semantic-scholar.config.yaml
The new field `keyFieldNameFromInclude` was introduced (and made required) as part of https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1338
That should hopefully fix the current failure of the two S2 pipelines.
> S2 pipelines: added missing keyFieldNameFromInclude

- deployments/data-hub/release-data-hub--stg.yaml
This should deploy the capability alongside the existing celery executor. Celery is used by default, and to use the k8s executor you should add a task to the `kubernetes` task queue (whatever that means for airflow dags?).
> feat(data-hub/stg): Deploy Data Hub Airflow chart with kubernetes executor

- deployments/data-hub/release-data-hub--stg.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/461
see also https://github.com/elifesciences/elife-flux-cluster/pull/2497
The rendered pod template didn't include the resources or volumes from extraVolumeMounts etc. As a workaround we are defining the pod template via stringOverride instead.
> Data Hub: Override Kubernetes Pod Template with correct volumes

- deployments/epp/prod/epp-kustomization.yaml
This commit updates the imagepolicy tags for several services in the epp-kustomization.yaml file. The tags for epp-server, epp-client, epp-import, and epp-biorxiv-xslt-api have been changed to include '-approved' for better distinction.
> feat: Update imagepolicy tags in epp-kustomization.yaml

- deployments/data-hub/sciety-labs/sciety-labs--prod.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/818
This may make it slightly more likely that all three OpenSearch nodes are being utilised. (Although now guarantee)
> Sciety Labs: Increased replicas to match number of OpenSearch nodes

- deployments/data-hub/sciety-labs/sciety-labs--prod.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/835
See https://github.com/elifesciences/elife-flux-cluster/pull/2561#issuecomment-1888650712
This is redirecting to `labs.sciety.org`
> Sciety Labs: Redirect to preferred host (via nginx)

- deployments/data-hub/sciety-labs/sciety-labs--stg.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/835
See https://github.com/elifesciences/elife-flux-cluster/pull/2561#issuecomment-1888650712
Follow on from failed attempt https://github.com/elifesciences/elife-flux-cluster/pull/2563
> Attempt a redirect to Preferred Host using `X-Forwarded-For` header

- deployments/data-hub/sciety-labs/sciety-labs--prod.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/835 See https://github.com/elifesciences/data-hub-issues/issues/835#issuecomment-1894222481
Example:
https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#taxing-rewrites
Which mentions we could maybe also use `return`.
And a similar issue:
https://stackoverflow.com/questions/28081159/nginx-request-uri-has-duplicated-query-parameter
Which quotes the [documentation](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite):
> If a replacement string includes the new request arguments, the previous request arguments are appended after them. If this is undesired, putting a question mark at the end of a replacement string avoids having them appended, for example:
>
>  rewrite ^/users/(.*)$ …
> Sciety Labs: Fixed duplicated query parameters when redirecting to preferred host

- deployments/data-hub/release-data-hub--stg.yaml
Updating schedule period of Google Spreadsheet Data Pipeline to "At minute 15 past every hour from 8 through 17 on every day-of-week from Monday through Friday."
cc: @fred-atherden @gnott
> [Data Hub Staging]: Update Google Spreadsheet Data Pipeline Scheduler Period

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
Add config to ingest OSF Preprints data from the Crossref Metadata API via our Generic Web API.
Depends on related Data Hub Core DAGs changes:
- https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1384
- https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1389
- https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1390
- https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1391
> Data Hub: Web API: Added Crossref Metadata API config for OSF Preprints

- kustomizations/apps/data-hub-configs/bigquery-to-opensearch--stg.yaml
This configures the ingestion of the Crossref metadata into OpenSearch.
Staging first, as there will need to be some Sciety Labs changes too.
> Data Hub: Ingest Crossref metadata into OpenSearch (staging)

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
depends on https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1401
Included the OSF preprint servers that were associated with the Centre of Open Science Crossref member and are listed in our preprint server list.
> Web API: Ingest Crossref metadata from multiple OSF preprint servers

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
fix for #2622 
This was because the line feeds were removed and everything after the first comment became a comment too.
> Web API: Fixed SQL query due to removed line feeds

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of elifesciences/data-hub-issues#854
Enabling provenance for Crossref pipeline allows us to see where the records came from (e.g. API url including the prefix used)
See https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1396
> Web API: Enable provenance for Crossref pipeline

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
MetaArXiv was missing from the OSF preprint server list.
EarthArXiv, EcoEvoRxiv and engrXiv are also in Crossref and supported by PREreview.
> Web API: Crossref pipeline: ingest MetaArXiv, EarthArXiv, EcoEvoRxiv and engrXiv

- deployments/epp/biophysics-colab/epp-client--biophysics-colab-kustomization.yaml
The epp-client container in the biophysics-colab deployment now includes commands for building and starting the application.
> [#1026] feat: add build and start commands to epp-client in biophysics-colab deployment

- deployments/data-hub/opensearch/prod/cluster.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/905
> OpenSearch: Increased memory requests to 6 GB (in prod)

- deployments/data-hub/release-data-hub--prod.yaml
Updated the GSheet pipeline hours to allow for updates early in the morning. Additionally, adjusted the end time to avoid updates after 7pm until the morning. This is to minimise the number of job runs during off peak hours.
> [Data Hub] Update GSheet data pipeline Scheduled hours

- kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml
Due to error:
> Error rendering Kubernetes Pod Spec: Cannot convert a non-kubernetes.client.models.V1Pod object into a KubernetesExecutorConfig
> Data Hub: CSV: Sciety Event: Removed executor_config

- kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml
depends on https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1447
> Data Hub: CSV Pipeline: Bring back pod_override

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
Using tags could help filtering DAGs using the Airflow UI
> Data Hub: Web API: Configure tags for Hypothesis pipeline (public reviews)

- deployments/data-hub/release-data-hub--prod.yaml
- deployments/data-hub/release-data-hub--stg.yaml
- deployments/data-hub/release-data-hub--test.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/646
The schedule interval is now part of the yaml config instead.
> Data Hub: Removed CSV and Web API schedule interval env variables

- kustomizations/apps/data-hub-configs/ga-data-pipeline.config.yaml
part of https://github.com/elifesciences/issues/issues/8759
The task was killed and with 450 MB base memory it was a bit close to the limit.
> Data Hub: GA UA: Increase pod memory to allow for more headroom

- kustomizations/apps/data-hub-configs/ga-data-pipeline.config.yaml
Related to https://github.com/elifesciences/issues/issues/8759
Some Yeam Month based Sciety metrics seem to be skewed for some months. Perhaps due to bots.
Retrieving daily data seems to be useful for that reason.
> Data Hub: GA UA: Sciety date based config

- kustomizations/apps/data-hub-configs/ga-data-pipeline.config.yaml
related to https://github.com/elifesciences/issues/issues/8759
We already have date and pagePath dimensions.
We also have a config for the yearMonth dimension. This adds a config for just he date as a dimension (without additional dimension fields).
> Data Hub: GA UA: journal date only config (no additional dimension)

- docs/new-application-team.md
After working through an issue with basex-validator not writing updates back, I have updated the documentation to make reference to creating a deployment key secret and how/when to reference it.
While there, I've corrected a few other out of date descriptions and paths.
> Update new-application-team.md document to help setup a writable repo if required

- kustomizations/apps/data-hub-configs/spreadsheet-data-pipeline.config.yaml
It seems pipeline for 'unmatched manuscripts' is not working and probably config is overrides by 'override hypothesis matching'
> Merged configs for unmatched manuscripts and override hypothesis matching

- kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml
Currently we are facing memory issues because of not individually adjusted memory usege for kubernetesExecutor pods. For now we are changing it back to Celery Executor.
> Rollbacked KubernetesExecutor from CSV pipelines

- kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml
following from this fix: https://github.com/elifesciences/data-science-dags/pull/636
And it seems sciety_events pod now only using the defined one in CSV config which is 1Gi.
> KubernetesExecutor config added back for CSV pipeline

- deployments/data-hub/release-data-hub--prod.yaml
- deployments/data-hub/release-data-hub--stg.yaml
This is to improve evaluated only search delay.
We believe EuropePMC is reading LabsLink in the evening, but it could be any time. We are now updating Sciety data hourly.
So running it hourly would make sense.
(The CSV import should be finished 40 past the hour)
The LabsLink pipeline itself only takes a few seconds. It does currently build up the whole XML structure in memory.
> Data Hub: EuropePMC LabsLink: Change schedule to hourly

- kustomizations/apps/data-hub-configs/bigquery-to-opensearch--stg.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/963
This adds ingest pipelines to calculate the following `calculated` fields:
- `doi_prefix` (extracted from `doi`)
- `publication_date` (select from `crossref` or `europepmc`)
- `title_with_markup` (select from `crossref`, `europepmc` or `s2`)
- `abstract_with_markup` (select from `crossref`, `europepmc` or `s2`)
This will allow us to just search over the `calculated` fields.
Depends on https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1491
Depends on https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1492
> Data Hub: OpenSearch: Configured ingest pipelines (Staging)

- deployments/data-hub/opensearch/staging/cluster.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/963
This is necessary to make use of the newly configured ingest pipelines (via #2911).
Trying to apply the ingest pipeline failed.
```http
POST preprints_v2/_update_by_query?pipeline=preprints_v2_default_pipeline
```
```json
{
"error": {
"root_cause": [
{
"type": "illegal_state_exception",
"reason": "There are no ingest nodes in this cluster, unable to forward request to an ingest node."
}
],
"type": "illegal_state_exception",
"reason": "There are no ingest nodes in this cluster, unable to forward request to an ingest node."
},
"status": 500
}
```
> OpenSearch: enabled `ingest` role (Staging)

- kustomizations/apps/data-hub-configs/bigquery-to-opensearch--prod.yaml
- kustomizations/apps/data-hub-configs/bigquery-to-opensearch--stg.yaml
Somewhat related to: https://github.com/elifesciences/data-hub-issues/issues/963
There are a few upper case DOIs in S2.
And as it happened, all version conflcts while applying the ingest pipeline had uppercase DOIs.
> Data Hub: OpenSearch: Convert S2 doi to lower case to avoid issues

- deployments/data-hub/opensearch/staging/cluster.yaml
Related to https://github.com/elifesciences/data-hub-issues/issues/963
Currently the index seem to be 91 GB in size. Although it may be able to shrink somehow if it removed deleted documents.
> OpenSearch: Increased disk size (staging)

- kustomizations/apps/data-hub-configs/kubernetes-pipeline.config.yaml
It is currently falling back to the `ci` deployment env.
This sets it to `staging`. Although ideally we could inherit the deployment env.
> Data Hub: K8s pipeline: Configure deployment env

- kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
> Added config for `Web_API_elife_observer_api_publication_dates_Kubernetes`

- kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
We ran out of memory for the lower limits.
This is now using the default values for the KubernetesExecutor.
We will decrease the resources after we are able to measure the actual usage.
> Data Hub: K8s: Increase resources for Data Science pipeline

- kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
part of AIRFLOW_APPLICATIONS_DIRECTORY_PATH
The environment variable points to path in our combined Airflow image.
For the `data-science-dags` image, the `notebooks` are within the working directory and it should find it automatically.
Alternatively we could set `AIRFLOW_APPLICATIONS_DIRECTORY_PATH` to the working directory.
> Data Hub: K8s: Data Science Dags: Remove AIRFLOW_APPLICATIONS_DIRECTORY_PATH

- kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
We observed memory usage of around 800 MB.
CPU usage appeared to be around 0.134.
> Data Hub: K8s: Data Science DAGs: Reduce memory requirements

- kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
follow up to: #3026
Encountered OOM with just 1Gi (even though the charts showed lower usage).
> staging-data-science-peerscout-build-reviewing-editor-profiles-kubernet-3vuqxdbq   0/1     OOMKilled   0               7m13s
> Data Hub: K8s: Data Science DAGs: Increase to 2Gi due to OOM

- kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
> Data Hub: K8s: Data Science DAGs: Removed AIRFLOW_APPLICATIONS_DIRECTORY_PATH again after updating data-science-dags image

- kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml
- kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
Generally we want to avoid running the same DAG concurrently.
>    :param max_active_runs: maximum number of active DAG runs, beyond this
>        number of DAG runs in a running state, the scheduler won't create
>        new active DAG runs
> Data Hub: K8s: Avoid concurrent DAG runs

- deployments/data-hub/data-hub-api/data-hub-api--prod.yaml
- deployments/data-hub/data-hub-api/data-hub-api--stg.yaml
related to https://github.com/elifesciences/data-hub-issues/issues/994
It seems all of those settings are per IP address.
Maybe we could remove `limit-rps`.
Ideally there would could limit the number of concurrent connections irrespective of the IP.
[Documentation](https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#rate-limiting)
These annotations define limits on connections and transmission rates. These can be used to mitigate [DDoS Attacks](https://www.nginx.com/blog/mitigating-ddos-attacks-with-nginx-and-nginx-plus).
> - nginx.ingress.kubernetes.io/limit-connections: number of concurrent connections allowed from a single IP address. A 503 error is returned when exceeding this limit.
> - nginx.ingress.kubernetes.io/limit-rps: number …
> Data Hub API: Limit concurrent connections by IP to 3

- deployments/data-hub/release-data-hub--prod.yaml
- deployments/data-hub/release-data-hub--stg.yaml
- deployments/data-hub/release-data-hub--test.yaml
Except the `worker`.
We also added config for `redis` (but no resources config for it yet).
> Data Hub: Move other Airflow services to data-hub-services node pool

- deployments/data-hub/release-data-hub--prod.yaml
- deployments/data-hub/release-data-hub--stg.yaml
- deployments/data-hub/release-data-hub--test.yaml
It looks like we need to configure those options within the `master` instead
> Data Hub: Fix postgresql and redis tolerations and node selector config

- deployments/data-hub/release-data-hub--prod.yaml
- deployments/data-hub/release-data-hub--stg.yaml
- deployments/data-hub/release-data-hub--test.yaml
airflow-web keeps getting killed before it was able to start up.
> Data Hub: Allow more time for airflow-web to start

- deployments/data-hub/release-data-hub--prod.yaml
We observed up to 4 GB previously.
We think it may get killed due to sudden high memory usage that isn't recorded.
> Data Hub: Increase postgresql requests and limits (prod)

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
This was accidentally commented out in the previous PR
> Data Hub: Web API: Enable cursor pagination for OpenAlex

- kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
The correct temp directory seem to be `/var/tmp`:
```console
$ ls -la /var/tmp/tmpx8otzcsa/
total 524544
drwx------ 2 airflow root        41 Oct 18 10:51 .
drwxrwxrwt 1 root    root        25 Oct 18 10:51 ..
-rw-r--r-- 1 airflow root 299769736 Oct 18 10:59 downloaded_jsonl_data.jsonl
```
Otherwise `/tmp` stays empty:
```console
$ ls -la /tmp
total 20
drwxr-xr-x 3 root root  4096 Oct 18 10:51 .
drwxr-xr-x 1 root root   110 Oct 18 10:51 ..
drwx------ 2 root root 16384 Oct 18 10:51 lost+found
```
> Data Hub: K8s: Mount large-temp-volume to correct path

- kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
Back to mounting to /tmp
Setting TMPDIR in the hope that it will then use that.
> Data Hub: K8s: Attempt to fix large-temp-volume mount for OpenAlex pipeline

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
Follow-up to https://github.com/elifesciences/elife-flux-cluster/pull/3080
This adds the missing state file config.
Without the state file, other relevant config wasn't used.
> Data Hub: Web API: OpenAlex: Added missing state file config

- kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
To ensure it is using the latest image for the OpenAlex pipeline as we can't rely on the [image pull policy in combination with spegel](https://github.com/spegel-org/spegel/blob/main/docs/FAQ.md#why-am-i-not-able-to-pull-the-new-version-of-my-tagged-image).
In this case it would still continue to work with the previous image but effectively ignore the publication date filter.
> Data Hub: K8s: Use explicit tag for OpenAlex pipeline instead of latest

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
see https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1548
> Data Hub: Web API: Configure retry and same next cursor behaviour for Crossref and OpenAlex pipeline

- deployments/data-hub/external-secrets/openalex-api.yaml
- kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/1019
> Data Hub: Web API: Updated OpenAlex web config to use updated_date filter instead

- kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/1020
> Data Hub: Web API: Added biorxiv_medrxiv_meca_path_metadata_v2 pipeline

- kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
It was failing with something like:
> [2024-12-06, 17:29:58 UTC] {pod_manager.py:418} INFO - [base]   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
> [2024-12-06, 17:29:58 UTC] {pod_manager.py:418} INFO - [base]     return _run_code(code, main_globals, None,
> [2024-12-06, 17:29:58 UTC] {pod_manager.py:418} INFO - [base]   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
> [2024-12-06, 17:29:58 UTC] {pod_manager.py:418} INFO - [base]     exec(code, run_globals)
> [2024-12-06, 17:29:58 UTC] {pod_manager.py:418} INFO - [base]   File "/opt/***/data_pipeline/generic_web_api/cli.py", line 3, in <module>
> [2024-12-06, 17:29:58 UTC] {pod_manager.py:418} INFO - [base]     from data_pipeline.generic_web_api.generic_web_api_config import (
> [2024-12-06, …
> Data Hub: K8s: Web API: Fixed OpenAlex pipeline after Python 3.9 upgrade

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
The property `urlSourceType` has been renamed a while ago for clarity but we hadn't made the change in the flux config.
```yaml
urlSourceType:
name: <request builder name>
sourceTypeSpecificValues:
...
```
should be:
```yaml
requestBuilder:
name: <request builder name>
parameters:
...
```
> Data Hub: Web API: Replaced deprecated `urlSourceType` with `requestBuilder`

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
related to https://github.com/elifesciences/data-hub-issues/issues/1048
This should use the new `spacy_batch_keyword_extraction_api`.
> Data Hub: Web API: Fixed SpaCy request builder

- deployments/peerscout/spacy-keyword-extraction-api/spacy-keyword-extraction-api--prod.yaml
Related to https://github.com/elifesciences/data-hub-issues/issues/1046
This is to allow it to process keywords faster. At least temporarily.
> PeerScout: SpaCy API: Increased CPU limit

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
related to https://github.com/elifesciences/data-hub-issues/issues/1048
related to https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1583
Increase max source values per request to reduce API overhead.
Reduce batch size to write to BigQuery more frequently.
i.e.
from: every 100 batches or 100 * 10 = 1000 records
to: every 25 batches, or 25 * 20 = 500 records
> Data Hub: Web API: Adjust batch size and max source values per request

- deployments/peerscout/spacy-keyword-extraction-api/spacy-keyword-extraction-api--prod.yaml
related to https://github.com/elifesciences/data-hub-issues/issues/1047
Sometimes the configured max source values can and concurrent requests can cause it to process requests slower than 60 seconds. This gives it up to 5m to process requests.
> PeerScout: SpaCy API: Increase timeout to 5m

- deployments/peerscout/spacy-keyword-extraction-api/spacy-keyword-extraction-api--prod.yaml
Related to https://github.com/elifesciences/data-hub-issues/issues/1046
Up from 2
(While pipelines are catching up, we have 4 running - 2 for staging, 2 for prod)
> PeerScout: Spacy API: Increase replicas further to 3 (prod)

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
related to https://github.com/elifesciences/data-hub-issues/issues/1052
depends on https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1584
> Data Hub: Web API: Timeout for SpaCy keyword extraction pipelines (120 seconds)

- kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
related to https://github.com/elifesciences/data-hub-issues/issues/1053
re-extract keywords with new spacy version. That wil allow us to compare the extracted keywords to ensure that they haven't changed.
> Data Hub: Web API: Re-extract keywords after SpaCy upgrade to 2.3.9

- kustomizations/apps/data-hub-configs/kubernetes-pipeline-other-pipelines--stg.config.yaml
Fix for `[2025-01-24, 17:42:16 UTC] {pod_manager.py:418} INFO - [base] Invalid bucket name "{ENV}-elife-data-pipeline": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
`
> [Data Hub]: Remove placeholder for DEPLOYMENT_ENV

- deployments/data-hub/release-data-hub--prod.yaml
- deployments/data-hub/release-data-hub--stg.yaml
related to https://github.com/elifesciences/data-hub-issues/issues/1073
We meant to run this pipeline every 20 mins but it seems like it is running only at past 20. So we need to first update this.
> [Data Hub]: Update Google SpreadSheet pipeline schedular interval

- system/gitops-dashboard/release.yaml
Not sure if this makes sense at all. But since I am encountering random errors, could that be the cause?
> Switch to regular oauth proxy for the Weave GitOps dashboard

- .tool-versions
- scripts/validate.sh
- **upgrade kubeconform**
- **exclude patches from kubeconform, and put debugging behind ENV var for github actions debug, and add more output on failure**
- **Clone repo for offline schemas instead of relying on githubusercontent requests**
> Fix kubeconform throwing 429 from githubusercontent.com

- deployments/epp/staging/deployment-scaledobject.yaml
- kustomizations/services/temporal/worker/deployment-scaledobject.yaml
This should ensure that workers on Temporal are scaled automatically based on the workload thus saving resources and costs.
> Implement KEDA autoscaler for Temporal workers

- nodes/clusters/end-to-end-tests/nodes/1_large_simulated_node.yaml
- nodes/clusters/end-to-end-tests/nodes/4_smaller_simulated_nodes.yaml
- tests/run_cluster_in_kind.sh
Add topology labels so that we can effectively test topology aware deployments
> deploy(clusters/end-to-end-tests,tests): Add topology labels
