renovate.json
=> removes me from the assignees list

deployments/reviewer/libero-reviewer--prod.yaml
=> Update reviewer-client to latest image

deployments/reviewer/libero-reviewer--prod.yaml
Also use timestamped tag to make tracking images easier.
=> feat(reviewer): Update reporter to include ignored submissions

deployments/editor/libero-editor--prod.yaml, deployments/editor/libero-editor--stg.yaml
Currently we have a mongo error of `Retryable writes are not supported` I'm hoping this param fixes this.
=> fix(editor): update db query to not retry writes

deployments/reviewer/libero-reviewer--prod.yaml
Updates production to...
- liberoadmin/reviewer-client master-aed10b72-20210124.2236
- liberoadmin/reviewer-submission master-4960d173-20210119.1137
- liberoadmin/continuum-adaptor master-73b9f4bb-20210115.1716
This closes elifesciences/issues#6358, closes elifesciences/issues#6378
=> feat(reviewer): deploy latest version to production

deployments/editor/libero-editor--prod.yaml, deployments/editor/libero-editor--stg.yaml
Await the changes to editors formula chart before merging in.
=> feat(editor): add basex-transformer to deployment

deployments/data-hub/data-hub--stg.yaml
Reduced the value of AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL  to see if this positively affects time between task runs in staging
=> fix(data-hub): Reduced the value of AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL 

renovate.json, system/monitoring/prometheus-operator.yaml
See bug https://github.com/elifesciences/issues/issues/7216
=> fix(prometheus): temporarily stop prometheus automatic upgrades and rollback to previous version

deployments/data-hub/data-hub--stg.yaml
added new image tag for staging
=> updated image for data-hub staging

deployments/data-hub/data-hub--stg.yaml
=> [data-hub staging] image tag update

deployments/epp-node-prototype/deployment.yaml, deployments/epp-node-prototype/ingress.yaml, deployments/epp-node-prototype/namespace.yaml, deployments/epp-node-prototype/services.yaml
As a test what happens when multiple clusters are asked to update DNS records.
=> release(epp-node): Deploy the EPP-node application to the prod cluster

deployments/data-hub/data-hub--stg.yaml
https://github.com/elifesciences/data-hub-issues/issues/369
=> [data-hub] staging image tag is updated

deployments/data-hub/data-hub--prod.yaml
https://github.com/elifesciences/data-hub-issues/issues/369
=> [data-hub prod] upgraded data-hub prod tag

deployments/data-hub/data-hub--prod.yaml, deployments/data-hub/data-hub--stg.yaml, deployments/data-hub/data-hub-configs.yaml
https://github.com/elifesciences/data-hub-issues/issues/333
=> [data-hub prod] added open research gmail account pipeline configurations

system/infra/ingress-nginx-controller.yaml
Also need to update values for new chart so that ingresses without an IngressClass set are still configured.
=> release(nginx-ingress): update to latest release of nginx-ingress

deployments/data-hub/data-hub--stg.yaml, deployments/data-hub/data-hub-configs.yaml
=> deploy europepmc pipeline to staging

deployments/data-hub/data-hub--stg.yaml
https://github.com/elifesciences/data-hub-issues/issues/388
=> [data-hub-staging image update] editor recommendation memory usage

deployments/data-hub/data-hub--stg.yaml
=> updated data hub staging image tag to ad82a8 (EuropePMC pipeline fix)

deployments/data-hub/data-hub--prod.yaml
similar to #514 
but this time for the prod image
(image is still being built)
=> updated Data Hub Prod image tag to 0.0.91

deployments/data-hub/data-hub-configs.yaml
Increasing the batch size to reduce the number of calls to BigQuery.
=> increase batch size for europepmc pipeline

deployments/data-hub/data-hub--prod.yaml
(the prod image is already up-to-date)
=> enable europepmc pipeline in prod

deployments/data-hub/data-hub--prod.yaml, deployments/data-hub/data-hub--stg.yaml
(still waiting for images to be built)
=> fix for europepmc pipeline infinite loop

deployments/data-hub/data-hub--stg.yaml
Reverts elifesciences/elife-flux-cluster#530
=> Revert "upgraded staging tag"

deployments/data-hub/data-hub--prod.yaml
deployment of https://github.com/elifesciences/data-hub-issues/issues/388
=> upgraded tag for data-hub prod image

deployments/data-hub/data-hub--stg.yaml
https://github.com/elifesciences/data-hub-issues/issues/398
=> upgraded data-hub staging img tag

deployments/data-hub/data-hub--prod.yaml
deployment of https://github.com/elifesciences/data-hub-issues/issues/398
=> upgraded data-hub prod img tag

deployments/reviewer/automations/updateautomation.yaml, deployments/reviewer/libero-reviewer--stg.yaml, deployments/reviewer/sciencebeam.yaml
NOTE: no automation for production reviewer deployments (except sciencebeam)
=> feat(reviewer): enable image update automation for staging and sciencebeam

deployments/data-hub/data-hub-configs.yaml, deployments/data-hub/release-data-hub--prod.yaml, deployments/data-hub/release-data-hub--stg.yaml
config required for the semantic scholar pipeline: https://github.com/elifesciences/data-hub-core-airflow-dags/pull/961
Left out the schedule interval for now to test it first by manually triggering it.
=> add semantic scholar pipeline config

deployments/peerscout/peerscout--prod.yaml, deployments/peerscout/source--prod.yaml
updating the Ingress in the chart
=> upgrade peerscout api image tag

deployments/data-hub/data-hub-configs.yaml
https://github.com/elifesciences/data-hub-issues/issues/415
=> added other elife used preprint servers to the europepmc pipeline

deployments/data-hub/release-data-hub--stg.yaml
https://github.com/elifesciences/data-hub-issues/issues/411
=> Update scheduler intervals (weekly-monthly)

deployments/data-hub/release-data-hub--stg.yaml, kustomizations/apps/data-hub-configs/kustomization.yaml, kustomizations/apps/data-hub-configs/semantic-scholar-recommendation.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/425
=> Semantic Scholar Recommendation Staging config

deployments/data-hub/release-data-hub--prod.yaml, system/monitoring/newrelic/release.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/425
depends on #627
(and new airflow image release)
=> semantic scholar recommendation prod config

deployments/data-hub/release-data-hub--stg.yaml
Reverts elifesciences/elife-flux-cluster#638
It seems changes not helped to solve the issue.
=> Revert "Webserver failure"

deployments/data-hub/release-data-hub--prod.yaml
https://github.com/elifesciences/data-hub-issues/issues/121
=> Airflow upgrade to version 2.3.0

deployments/data-hub/release-data-hub--stg.yaml, kustomizations/apps/data-hub-configs/elife-article-xml.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/393
=> [stg] Related article pipeline config

kustomizations/apps/data-hub-configs/kustomization.yaml
https://github.com/elifesciences/data-hub-issues/issues/393
=> added elife-article-xml.config.yaml config map file list

deployments/data-hub/release-data-hub--prod.yaml, deployments/data-hub/release-data-hub--stg.yaml
https://github.com/elifesciences/data-hub-issues/issues/393
=> [prod] Elife article xml pipeline configuration 

deployments/data-hub/release-data-hub--prod.yaml
missed adding the ELIFE_ARTICLE_XML_CONFIG_FILE_PATH
=> added ELIFE_ARTICLE_XML_CONFIG_FILE_PATH

deployments/data-hub/release-data-hub--stg.yaml, deployments/peerscout/peerscout--prod.yaml, deployments/peerscout/peerscout--stg.yaml
https://github.com/elifesciences/data-hub-issues/issues/443
https://github.com/elifesciences/data-hub-issues/issues/454
=> Define PeerScout API target dataset and changed sch period for article-xml pipeline

deployments/data-hub/release-data-hub--stg.yaml, deployments/data-hub/release-data-hub--test.yaml
Slightly higher for test to see if staggering helps
=> fix(data-hub): increase reconciliation interval for stg and test

deployments/data-hub/release-data-hub--prod.yaml
https://github.com/elifesciences/data-hub-issues/issues/464
=> Adding twitter API configuration to production

deployments/data-hub/release-data-hub--stg.yaml, deployments/data-hub/secrets/twitter-api-access-token-secret.yaml, deployments/data-hub/secrets/twitter-api-access-token.yaml, deployments/data-hub/secrets/twitter-api-key.yaml, deployments/data-hub/secrets/twitter-api-secret.yaml, kustomizations/apps/data-hub-configs/twitter-ads-api.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/475
=> [stg] Deployment of Twitter Ads API data pipeline for campaign details

kustomizations/apps/data-hub-configs/kustomization.yaml
Missed to add twitter-ads-api config file name to kustomization.yaml
=> Added twitter-ads-api.config.yaml file to  kustomization.yaml

deployments/data-hub/release-data-hub--prod.yaml, deployments/data-hub/release-data-hub--stg.yaml
https://github.com/elifesciences/data-hub-issues/issues/475
=> [data-hub prod] add configuration of Twitter Ads API

kustomizations/apps/data-hub-configs/semantic-scholar-recommendation.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/481
depends on https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1050 being merged and included in Data Hub Airflow Image.
=> configure Semantic Scholar Recommendation API key

kustomizations/apps/data-hub-configs/twitter-ads-api.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/477
=> [data-hub config] Added configuration for twitter campaign audience reach data pipeline

kustomizations/apps/data-hub-configs/twitter-ads-api.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/478
=> Added twitter ads api configuration

kustomizations/apps/data-hub-configs/twitter-ads-api.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/484
=> updated twitter ads api config according to code changes

kustomizations/apps/data-hub-configs/twitter-ads-api.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/486
=> [data-hub config] updated twitter ads api config

kustomizations/apps/data-hub-configs/twitter-ads-api.config.yaml
Changed to using start_date instead of end_date as this make it clearer
=> Twitter ads API config query update

kustomizations/apps/data-hub-configs/twitter-ads-api.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/479
=> Updated twitter cost sql query after initial load

deployments/data-hub/release-data-hub--stg.yaml
https://github.com/elifesciences/data-hub-issues/issues/494
=> Changed the article_xml_pipeline schedule interval for initial load in stg

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/497
=> retrieve public reviews from hypothesis

kustomizations/apps/data-hub-configs/twitter-ads-api.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/501
=> [data-hub] modified the twitter ads pipeline config sql query

kustomizations/apps/data-hub-configs/twitter-ads-api.config.yaml
Updated query to use calculated date including end_time of the request.
=> [data-hub] Updated twitter Ads Pipeline Config SQL Query

kustomizations/apps/data-hub-configs/europepmc.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/512
=> Added new config to write the whole EuropePMC response to BQ

kustomizations/apps/data-hub-configs/europepmc.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/510
=> added SciELO Preprints to EuropePMC pipeline config

.github/workflows/e2e.yaml, system/database/mongodb/psmdb-operator-release.yaml, system/database/mongodb/psmdb-operator-source.yaml, system/database/namespace.yaml
This is required for EPP to be deployed
References https://github.com/elifesciences/enhanced-preprints-server/issues/406
=> Add MongoDB operator to `flux-prod` cluster

deployments/epp/prod/mongodb-release.yaml, deployments/epp/staging/mongodb-release.yaml
related to https://github.com/elifesciences/enhanced-preprints-server/issues/419
=> fix(epp/psmdb): reduce verbosity of PSMDB

deployments/epp/prod/epp-kustomization.yaml, deployments/epp/staging/epp-kustomization.yaml, kustomizations/apps/epp/server/deployment.yaml
References https://github.com/elifesciences/enhanced-preprints-server/issues/419
=> Update EPP loglevel to error

kustomizations/apps/data-hub-configs/europepmc.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/520
=> EuropePMC config update to include all PPR and increase batch size

deployments/epp/prod/epp-kustomization.yaml, deployments/epp/staging/epp-kustomization.yaml, kustomizations/apps/epp/client/deployment.yaml
related https://github.com/elifesciences/enhanced-preprints-client/issues/104
=> Enable GTM env vars in the epp deployment

deployments/epp/prod/epp-kustomization.yaml, deployments/epp/staging/epp-kustomization.yaml, kustomizations/apps/epp/client/deployment.yaml
https://github.com/elifesciences/enhanced-preprints-server/issues/446
=> Set caching headers for EPP

kustomizations/apps/data-hub-configs/twitter-ads-api.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/522
=> [data-hub] updated table names and queries in config for twitter ads pipeline

deployments/podinfo/namespace.yaml, deployments/podinfo/prod/canary.yaml, deployments/podinfo/prod/deployment.yaml, deployments/podinfo/prod/ingress.yaml, deployments/podinfo/updateautomations/imagerepository.yaml, deployments/podinfo/updateautomations/podinfo-stable.yaml, deployments/podinfo/updateautomations/updateautomation.yaml
Revert "deploy(podinfo): remove podinfo to free capacity"
This reverts commit fd210ea7b499479f7a4cda9b27454ff3c0e8c1a6.
=> deploy(podinfo): reinstall podinfo

kustomizations/apps/data-hub-configs/twitter-ads-api.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/523
=> added all twitter accounts for every branch of twitter ad pipeline

deployments/data-hub/release-data-hub--stg.yaml
https://github.com/elifesciences/data-hub-issues/issues/537
=> changed crontab format for weekly dag to test if it will be triggered

deployments/data-hub/release-data-hub--stg.yaml
https://github.com/elifesciences/data-hub-issues/issues/537
=> [data hub staging] Add Airflow DB maintenance Environment Variables

deployments/data-hub/data-hub-api/data-hub-api--prod.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/549
=> added data-hub-api prod config

deployments/data-hub/data-hub-api/data-hub-api--prod.yaml, deployments/data-hub/data-hub-api/data-hub-api--stg.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/556
=> provide GCP credentials to data-hub-api

deployments/data-hub/data-hub-api/data-hub-api--prod.yaml, deployments/data-hub/data-hub-api/data-hub-api--stg.yaml
Fixes deployment issue:
```
deployments	master/031d9d3cb3efa406c429c9d958a8a5855501c4ff	False    	False	Deployment/data-hub/data-hub-api--prod validation error: cannot restore slice from map	
```
=> fix(data-hub/api): fix format of envvars in deployment

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/553
=> CrossRef Event Data: load data in daily batches

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/581
=> added bioRxiv/medRxiv MECA path metadata pipeline

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/557
~Addition to that : Removed initial load configurations for biorxiv MECA path~
=> [Data Hub] Add bioRxiv and medRxiv API data configurations

deployments/reviewer/redirects/staging/redirect-authorguide.yaml, deployments/reviewer/redirects/staging/redirect-contact.yaml, deployments/reviewer/redirects/staging/redirect-reviewprocess.yaml
relates to https://github.com/elifesciences/enhanced-preprints-issues/issues/403
=> Add redirects for reviewer staging aherad of 31st launch

deployments/epp/staging/epp-kustomization.yaml, kustomizations/apps/epp/image-server/deployment.yaml
relates to https://github.com/elifesciences/enhanced-preprints-issues/issues/509
=> Reconfigure IIIF server to use s3 in staging

kustomizations/apps/data-hub-configs/spreadsheet-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/642
=> added unmatched_manuscripts speardsheet in the pipeline

eks/addons/kube-proxy.yaml, system/autoscaler/release.yaml, system/kube-system/descheduler/release.yaml
related to https://github.com/elifesciences/issues/issues/8197
=> deploy(system/eks-addons,system/autoscaler,system/descheduler): upgrade eks and kubernetes addons to versions for EKS 1.23

kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/647
=> [Data Hub] Add manuscript_license csv config

.github/workflows/e2e.yaml
work needed prior to  https://github.com/elifesciences/enhanced-preprints-issues/issues/418
relates to https://github.com/elifesciences/enhanced-preprints-issues/issues/418
=> Upgrade flux version in CI

deployments/data-hub/release-data-hub--prod.yaml, deployments/data-hub/release-data-hub--stg.yaml, deployments/data-hub/release-data-hub--test.yaml
https://github.com/elifesciences/data-hub-issues/issues/643
Will update production in another PR after seeing staging env works ok with the changes.
=> Updated Airflow DB Maintenance schedule period from weekly to daily

deployments/data-hub/release-data-hub--prod.yaml
https://github.com/elifesciences/data-hub-issues/issues/643
=> Changed Prod Airlfow DB maintenance Schedular interval to daily

deployments/reviewer/redirects/staging/redirect-ejp.yaml
Add a redirect for for reviewer to eJP
=> Add a redirect for for reviewer staging to eJP

.github/workflows/e2e.yaml
fixes https://github.com/elifesciences/issues/issues/8217
=> Make the CI use the version of flux indicated in the prod cluster manifest

deployments/data-hub/data-hub-api/data-hub-api--prod.yaml
https://github.com/elifesciences/data-hub-issues/issues/656
=> Add latest relase of data hub api and automation back

kustomizations/apps/data-hub-configs/spreadsheet-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/679
=> import deleted_hypothesis_annotations table

kustomizations/apps/data-hub-configs/spreadsheet-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/711
=> [Data Hub] Add manual manuscript published date for DocMaps API

kustomizations/apps/data-hub-configs/spreadsheet-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/686
=> [Data Hub] Update table and sheet name in the config

deployments/data-hub/release-data-hub--prod.yaml, deployments/data-hub/release-data-hub--stg.yaml
https://github.com/elifesciences/data-hub-issues/issues/711
=> Update scheduler interval for google spreadsheet pipeline

deployments/epp/staging/epp-import.yaml, kustomizations/apps/epp/import/biorxiv-xslt-api/automations/policy.yaml, kustomizations/apps/epp/import/biorxiv-xslt-api/automations/repository.yaml, kustomizations/apps/epp/import/biorxiv-xslt-api/deployment.yaml, kustomizations/apps/epp/import/biorxiv-xslt-api/kustomization.yaml, kustomizations/apps/epp/import/biorxiv-xslt-api/service.yaml, kustomizations/apps/epp/import/deployment.yaml
Fix commonLabels for import while I'm at it.
=> deploy(kustomization/epp): update import to also deploy a biorxiv-xslt-api service to be used by epp-import, and configure epp-import to point to it. 

kustomizations/apps/data-hub-configs/elife-article-xml.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/738
=> [Data Hub]: Update article xml pipeline config

kustomizations/apps/data-hub-configs/elife-article-xml.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/738
=> [Data Hub]: Update article xml pipeline config with new version

kustomizations/apps/data-hub-configs/spreadsheet-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/761
=> Add config for MECA path updates

deployments/data-hub/sciety-labs/sciety-labs--prod.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/764
Using OpenSearch staging for now.
See previous PRs related to staging:
#2335
#2339
=> Sciety Labs: Configure OpenSearch for prod

deployments/data-hub/release-data-hub--prod.yaml, deployments/data-hub/release-data-hub--stg.yaml, kustomizations/apps/data-hub-configs/bigquery-to-opensearch--prod.yaml, kustomizations/apps/data-hub-configs/kustomization.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/763
=> Added OpenSearch Data Hub pipeline config for prod

deployments/data-hub/sciety-labs/sciety-labs--prod.yaml, deployments/data-hub/sciety-labs/sciety-labs--stg.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/765
to enable https://github.com/sciety/sciety-labs/pull/192
=> Sciety Labs: Configure OpenSearch Embedding Vector

deployments/peerscout/peerscout--prod.yaml
Added replicas to Peerscout API prod to increase availability
=> (Data Hup / Peerscout API): Add replicas to Peerscout API prod

kustomizations/apps/data-hub-configs/bigquery-to-opensearch--stg.yaml
=> OpenSearch: Load S2 and EuropePMC separately (staging)

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
https://github.com/elifesciences/enhanced-preprints-issues/issues/912
=> Add config for manual import for past MECA paths

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
https://github.com/elifesciences/enhanced-preprints-issues/issues/912
=> Add config for missing content in biorxiv_medrxiv_meca_path_metadata

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/798
depends on https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1334
=> Web API: Configured S2 Title Abstract Embeddings pipeline

kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/808
https://github.com/elifesciences/data-hub-issues/issues/811
=> Update insert method for CSV pipeline tables

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/810
=> Web API: Configure dataPipelineId for every config item

system/storageclasses/csi-ebs-high-iops.yaml
relates to https://github.com/elifesciences/data-hub-issues/issues/822
=> add a new storageclass for gp3

kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/813
depends on https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1350
Loads Sciety Events into BigQuery using CSV pipeline.
=> Data Hub CSV: Configure Sciety Events

deployments/data-hub/release-data-hub--stg.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/461
requires https://github.com/elifesciences/data-science-dags/pull/614
=> Data Hub: Make Data Science Recommendation DAG run via Kubernetes Executor

deployments/data-hub/release-data-hub--prod.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/461
initial PR #2497
fix https://github.com/elifesciences/elife-flux-cluster/commit/395e98c41db2da6bc7f30126c7869eb09d494094
(this isn't configuring any DAG to use the Kubernetes executor yet)
=> Data Hub: Configure Celery Kubernetes Executor for prod

deployments/data-hub/release-data-hub--prod.yaml
part of elifesciences/data-hub-issues#461
same as #2513 but for prod
=> Data Hub: Make Data Science Recommendation DAG run via Kubernetes Executor (prod)

kustomizations/apps/epp/client/deployment.yaml
Reverts elifesciences/elife-flux-cluster#2528
=> Revert "Make deployment use more memory for all environments"

kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/770
=> Add config for `ejp_preprint_server_dois_v2`

kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/770
=> Add config for `ejp_manuscript_version_notes`

kustomizations/apps/data-hub-configs/s3-csv-data-pipeline--test.config.yaml, kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/770
=> Data Hub: Remove unused CSV config

deployments/data-hub/release-data-hub--prod.yaml
https://github.com/elifesciences/data-hub-issues/issues/844
=> Data Hub Prod: Configured Kubernetes Executor for Keyword Extraction Pipeline

deployments/data-hub/data-hub-api/data-hub-api--prod.yaml
https://github.com/elifesciences/data-hub-issues/issues/852
=> [Data Hub]: Remove data-hub-api prod replica

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
This will be required for those papers to be returned by the related article functionality
=> Data Hub: Generate S2 Embeddings for OSF Preprints in Crossref

kustomizations/apps/data-hub-configs/bigquery-to-opensearch--prod.yaml
=> Data Hub: Ingest Crossref metadata into OpenSearch (prod)

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/881
=> Data Hub: Web API: Ingest bioRxiv etc Crossref metadata

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
See API docs:
https://api.crossref.org/swagger-ui
=> Web API: Crossref metadata API pipeline: Adding user agent to be "polite"

kustomizations/apps/data-hub-configs/bigquery-to-opensearch--prod.yaml, kustomizations/apps/data-hub-configs/bigquery-to-opensearch--stg.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/881
=> Data Hub: OpenSearch: Avoid importing non-preprints from Cold Spring Harbor Laboratory

kustomizations/apps/data-hub-configs/bigquery-to-opensearch--prod.yaml, kustomizations/apps/data-hub-configs/bigquery-to-opensearch--stg.yaml
Incorrect query was introduced by #2682
=> Data Hub: OpenSearch fixed Crossref query

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
=> Add `collections` to Data Hub

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of: https://github.com/elifesciences/data-hub-issues/issues/887
=> Update table name and API URL for the eLife collections list

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
=> Configure elife_collections_detail pipeline

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/887
=> Update sqlQuery in the config for collection details

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
=> Add `urlSourceType` for collection details data pipeline

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
=> Remove unnecessary `response` section from collection-details config

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
=> Add sourceTypeSpecificValues to collection details pipeline

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/887
=> Add only one example collection id to test (560cc395)

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
=> Update config to retrieve the whole list of collections

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/888
=> Configured `eLife podcast` import data pipeline

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/888
=> Changed podcast config to add episodes for each podcast

deployments/data-hub/release-data-hub--prod.yaml
https://github.com/elifesciences/data-hub-issues/issues/857
=> [Data Hub] Increased the scheduler period of Gsheet data pipeline

deployments/data-hub/release-data-hub--prod.yaml, deployments/data-hub/release-data-hub--stg.yaml, kustomizations/apps/data-hub-configs/ga-data-pipeline.config.yaml, kustomizations/apps/data-hub-configs/kustomization.yaml
part of https://github.com/elifesciences/issues/issues/8412
=> Data Hub: GA/UA pipeline: Added temporary config to retrieve data before deadline

kustomizations/apps/data-hub-configs/ga-data-pipeline.config.yaml
part of https://github.com/elifesciences/issues/issues/8759
Added more combinations of dimensions and metrics.
=> Data Hub: GA UA: Retrieve more data from UA

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/931
=> [Data Hub]: Added configuration for updated RP VOR

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/931
=> [Data Hub] Remove overwrite policy

kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml
=> Data Hub: CSV Pipeline: Run sciety_events in Kubernetes

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/646
depends on https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1448
=> Data Hub: Web API: Run hypthesis pipeline for public reviews hourly

kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml
=> Data Hub: CSV Pipeline: Fixed memory value in pod_override

kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml, kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
Depends on https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1449
The schedule for those pipelines will need to be configured via the yaml config instead.
=> Data Hub: CSV and Web API: Configure default config

kustomizations/apps/data-hub-configs/ga-data-pipeline.config.yaml
Related to https://github.com/elifesciences/issues/issues/8759
Depends on https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1450
This should help not getting killed midway.
=> Data Hub: GA UA: Airflow Config to run via Kubernetes Executor

kustomizations/apps/data-hub-configs/ga-data-pipeline.config.yaml
part of https://github.com/elifesciences/issues/issues/8759
This adds the following dimension combinations:
- yearMonth + userType + Channel Grouping + Source + Medium + Social Network + Adwords Destination URL + pagePath + pageTitle (Journal)
- yearMonth + Channel Grouping + Source + Medium + Social Network + Campaign + Landing Page + pagePath + pageTitle (Journal)
- yearMonth (Sciey)
=> Data Hub: GA UA: Add more data combination

kustomizations/apps/data-hub-configs/ga-data-pipeline.config.yaml
Part of https://github.com/elifesciences/issues/issues/8759
=> Data Hub: GA UA: added Sciety yearMonth + page and journal events

kustomizations/apps/data-hub-configs/spreadsheet-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/944
=> Add config for override_hypothesis_matching

kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml
=> Data Hub: CSV: Add name with env suffix to pod_override

deployments/data-hub/release-data-hub--prod.yaml, deployments/data-hub/release-data-hub--stg.yaml, kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml
part of: https://github.com/elifesciences/data-hub-issues/issues/843
=> Define KubernetesExecutor Pod Labels

kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/843
=> Use Kubernetes Executor in CSV pipelines

deployments/data-hub/release-data-hub--prod.yaml
Part of https://github.com/elifesciences/data-hub-issues/issues/843
=> Reduced memory usage for k8 pod template

deployments/data-hub/release-data-hub--prod.yaml
This reverts commit 91ac197e95758d64d592122bd2246836f42a4c32.
=> Revert "reduced memory usage for k8 pod template"

kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml
=> Data Hub: CSV: Add missing `airflow` parent to sciety events config

deployments/data-hub/opensearch/prod/cluster.yaml
part of elifesciences/data-hub-issues#963
Same as #2912 but for prod
=> OpenSearch: enabled ingest role (Prod)

kustomizations/apps/data-hub-configs/kubernetes-pipeline.config.yaml
=> Data Hub: Added missing gcloud credentials

kustomizations/apps/data-hub-configs/kubernetes-pipeline.config.yaml
=> Data Hub: K8s pipeline: Add keyword extraction

kustomizations/apps/data-hub-configs/kubernetes-pipeline.config.yaml
=> Data Hub: K8s: Add missing AWS credentials

kustomizations/apps/data-hub-configs/kubernetes-pipeline.config.yaml
=> [Data Hub]: Configure `resources` for k8s pipeline

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Data Hub: K8s pipeline: Fix `{ENV}` placeholder

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
I disabled the "traditional" DAGs
=> Data Hub: K8s pipeline: Configure schedules to replace "traditional" DAGs

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Add config for: `BigQuery_To_OpenSearch_Pipeline_Kubernetes`

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/966
=> Add AWS credentials to Openseacrh k8s pipeline

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml
=> Add config for opensearch k8s pipeline in prod

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Add config for `EuropePmc_Pipeline_Kubernetes`

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml
=> Add prod config for `EuropePmc_Pipeline_Kubernetes`

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Add config for EuropePmc_Pipeline_Labslink_Kubernetes (staging)

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Correct pipeline name with EuropePmc_Labslink_Pipeline_Kubernetes

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml
=> Add config for `EuropePmc_Pipeline_Labslink_Kubernetes` (prod)

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml
=> Update cli name to cli_europepmc (prod)

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Add config for `Materialize_BigQuery_Views_Pipeline_Kubernetes` (staging)

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Add 'Kubernetes' tag for the dags running with KubernetesPodOperator

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml
=> Add config for 'Materialize_BigQuery_Views_Pipeline_Kubernetes' (prod)

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Added Web_API_Pipeline_Kubernetes

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Add all web api pipeline Kubernetes config for staging

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Configure 'Data_Science_PeerScout_Build_Reviewing_Editor_Profiles_Kubernetes'

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Data Hub: K8s: Configure application path for data science notebooks

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Data Hub: Configure to use 'elifesciences/data-science-dags' image

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Add Kubernetes config for rest of the data science dags

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
part https://github.com/elifesciences/data-hub-issues/issues/965
=> Increased memory request for Data_Science_PeerScout_Recommend_Reviewing_Editors_Kubernetes

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml
=> Data Hub: k8s, Prod: Configured data science pipeline with Kubernetes

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
Removed config for paused pipeline
=> Remove config for Web_API_twitter_api_v2_search_for_preprints_and_user_Kubernetes

teams/data-hub/kustomization.yaml, teams/data-hub/nodepool-services.yaml
We want to protect main Data Hub services from other workloads.
=> Data Hub: Create data-hub-services node pool

deployments/data-hub/release-data-hub--prod.yaml, deployments/data-hub/release-data-hub--stg.yaml, deployments/data-hub/release-data-hub--test.yaml
=> Data Hub: Moved web to data-hub-services node pool

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml, kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
=> Data Hub: Web API: Ingest data from OpenAlex

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Data Hub: K8s: Configure large temp volume for OpenAlex pipeline

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Data Hub: K8s: Added karpenter.sh/do-not-disrupt for OpenAlex pipeline

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Data Hub: K8s: Run OpenAlex pipeline as root

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Data Hub: K8s: Add PYTHONPATH to OpenAlex pipeline after running as root

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
depends on https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1547
=> Data Hub: Web API: OpenAlex: chunk data by publication date

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
Also extract `publication_year` as we do not alway have a `publication_date` available.
=> Data Hub: Web API: OpenAlex: Extract `publication_year` and `display_name`

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
includes ability to configure retry
https://github.com/elifesciences/data-hub-core-airflow-dags/pull/1548
https://github.com/elifesciences/elife-flux-cluster/pull/3086
=> Data Hub: K8s: Web API: Update image tag for OpenAlex pipeline

deployments/data-hub/automations/data-hub-core-dags-stable-policy.yaml, deployments/data-hub/automations/data-hub-core-dags-stable-source.yaml, deployments/data-hub/automations/data-hub-core-dags-unstable-policy.yaml, deployments/data-hub/automations/data-hub-core-dags-unstable-source.yaml, deployments/data-hub/automations/data-hub-data-science-dags-stable-policy.yaml, deployments/data-hub/automations/data-hub-data-science-dags-stable-source.yaml, deployments/data-hub/automations/data-hub-data-science-dags-unstable-policy.yaml, deployments/data-hub/automations/data-hub-data-science-dags-unstable-source.yaml, deployments/data-hub/automations/data-hub-peerscout-dags-stable-policy.yaml, deployments/data-hub/automations/data-hub-peerscout-dags-stable-source.yaml, deployments/data-hub/automations/data-hub-peerscout-dags-unstable-policy.yaml, deployments/data-hub/automations/data-hub-peerscout-dags-unstable-source.yaml, deployments/data-hub/data-hub-configs.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
For review if you're happy with this
Lean on the CD automation framework to lookup the "latest" image, and inject it into the data-hub configs via string substitution.
=> Data hub inject pod image

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml
Just revert the placeholders in the production config.
=> Data Hub: K8s: Reverted placeholders in production due to not being replaced

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml
Reverts elifesciences/elife-flux-cluster#3090
=> Revert "Data Hub: K8s: Reverted placeholders in production due to not being replaced"

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/1006
=> Add toggl and twitter API keys to staging kubernetes config

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/1006
=> Added CiviCRM secret to kubernetes config staging

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/1006
=> Remove config for `Web_API_crossref_event_data_for_biorxiv_medrxiv_Kubernetes`

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/1006
=> Run web API pipelines via Kubernetes Pipeline on prod

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> [Data Hub / staging] Add Kubernetes pipeline config for `S3_XML_Data_Pipeline_Kubernetes`

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> [Data Hub staging] Update image tag for `S3_XML_Data_Pipeline_Kubernetes`

deployments/data-hub/automations/data-hub-ejp-xml-pipeline-unstable.yaml, deployments/data-hub/data-hub-configs.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> [Data Hub staging] Add image policy for unstable XML pipeline image

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml
=> [Data Hub prod]: Add config for `S3_XML_Data_Pipeline_Kubernetes`

deployments/data-hub/automations/data-hub-ejp-xml-pipeline-stable.yaml, deployments/data-hub/data-hub-configs.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml
=> [Data Hub prod] Add image policy for prod XML pipeline

deployments/data-hub/automations/data-hub-ejp-xml-pipeline-stable.yaml
fix of https://github.com/elifesciences/elife-flux-cluster/pull/3129
=> [Data Hub prod] Fix image policy for XML pipeline stable

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/1022
=> Update config for biorxiv_medrxiv_meca_path_metadata_v2 with batchsize

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
related to https://github.com/elifesciences/data-hub-issues/issues/1022
=> Removed urlSourceType for the Web APIs that uses placeholder

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/1022
=> Data Hub: Web API: Enable bioRxiv mecapath v2 in prod

tests/resources_to_test.txt
https://github.com/elifesciences/issues/issues/9065
=> fix external-dns tests

kustomizations/apps/data-hub-configs/s3-csv-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/633
=> Add config for datascience_person_roles_current pipeline

deployments/peerscout/spacy-keyword-extraction-api/spacy-keyword-extraction-api--prod.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/1045
=> PeerScout: Deploy SpaCy Keyword Extraction for prod

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml, kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
=> Data Hub: Web API: Added `keywords_from_manuscript_abstract` pipeline

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Data Hub: K8s: Web API: Added missing `_Kubernetes` suffix

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
=> Add `SpaCy` tag to related pipelines

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml, kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
=> Add config for `Web_API_keywords_from_disambiguated_editor_papers_abstract`

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml
=> [Data Hub prod]: Add config for Web_API_keywords_from_disambiguated_editor_papers_abstract

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/1047
related to https://github.com/elifesciences/data-hub-issues/issues/1048
also includes https://github.com/elifesciences/data-hub-issues/issues/1049
=> Use SpaCy batch extract keywords endpoint

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
Follow-up to #3220
part of elifesciences/data-hub-issues#1047
related to elifesciences/data-hub-issues#1048
also includes elifesciences/data-hub-issues#1049
=> Data Hub: K8s: Fixed data pipeline id for SpaCy batch keyword extraction pipelines

kustomizations/apps/data-hub-configs/web-api-data-pipeline.config.yaml
related to https://github.com/elifesciences/data-hub-issues/issues/1048
=> Data Hub: Web API: Fixed SpaCy disambiguate editor papers query

deployments/peerscout/peerscout--stg.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/1047
=> [Data Hub - staging] Use SpaCy Keyword Extraction API in PeerScout API 

deployments/peerscout/peerscout--prod.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/1047
=> PeerScout: Use SpaCy Keyword Extraction API in prod

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/1062
=> Data Hub: Web API: Enabled Vistaly Update Metrics pipeline in prod

kustomizations/apps/data-hub-configs/kubernetes-pipeline--prod.config.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
related to https://github.com/elifesciences/data-hub-issues/issues/1003
=> [Data Hub]: Remove unnecessary `imagePullPolicy` from Kubernetes config

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
related to https://github.com/elifesciences/data-hub-issues/issues/1003
=> [Data Hub - stg]: Read config parts from default config for Elife_Article_Xml_Pipeline_Kubernetes

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
Added the config part back which removed in this https://github.com/elifesciences/elife-flux-cluster/pull/3271 PR by mistake
=> [Data Hub -stg]: Fix the config (added github-api-secret-volume back)

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/1003
=> [Data Hub stg]: Remove default configs from stg kubernetes pipeline configs

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/1003
=> Data Hub: K8s: Fixed importFilesFrom key in config file

kustomizations/apps/data-hub-configs/kubernetes-pipeline--stg.config.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline-ejp-xml-pipelines--stg.config.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline-other-core-pipelines--stg.config.yaml, kustomizations/apps/data-hub-configs/kustomization.yaml
=> [Data Hub -stg]: Move eJP XML pipeline to a separate config

kustomizations/apps/data-hub-configs/kubernetes-pipeline-web-api-pipelines--stg.config.yaml
=> Data Hub: K8s: Move more common Web API config to defaults

kustomizations/apps/data-hub-configs/kubernetes-pipeline-data-science-pipelines--stg.config.yaml
=> Data Hub: K8s: Move more common Data Science config to defaults

kustomizations/apps/data-hub-configs/kubernetes-pipeline-ejp-xml-pipelines--stg.config.yaml
=> [Data Hub - stg]: Remove unnecessary default config from eJP XML K8s pipeline config

kustomizations/apps/data-hub-configs/kubernetes-pipeline-other-core-pipelines--stg.config.yaml
=> Data Hub: K8s: Moved other core pipelines resources to defaults

kustomizations/apps/data-hub-configs/kubernetes-pipeline-data-science-pipelines--stg.config.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline-other-core-pipelines--stg.config.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline-web-api-pipelines--stg.config.yaml
part of https://github.com/elifesciences/data-hub-issues/issues/1072
=> [Data Hub - stg]: Move image config to default for k8s pipelines

kustomizations/apps/data-hub-configs/kubernetes-pipeline-other-core-pipelines--prod.config.yaml, kustomizations/apps/data-hub-configs/kubernetes-pipeline-other-core-pipelines--stg.config.yaml
https://github.com/elifesciences/data-hub-issues/issues/1074
=> [Data Hub]: Update Schedular Interval for Materialized Views Pipeline to run 30 min frame

system/template-controller/release.yaml, system/template-controller/source.yaml
=> deploy(template-controller): migrate to new template controller helm chart delivered via oci elifesciences/issues#9153

kustomizations/apps/epp/preview/ingress.yaml
=> feat(kustomization/epp/preview): add tls to ingress definition and letsencrypt issuer to ingress elifesciences/issues#8974

crds/ack-controllers/common/services.k8s.aws_adoptedresources.yaml, crds/ack-controllers/common/services.k8s.aws_fieldexports.yaml, crds/ack-controllers/common/update.sh, crds/update_all.sh
=> deploy(crds/ack-controllers/common): manage and update the shared ACK controller CRDs 

system/clusterclasses/base/kustomization.yaml, system/nidhogg/kustomization.yaml, system/nidhogg/namespace.yaml, system/nidhogg/release.yaml, system/nidhogg/source.yaml, system/spegel/kustomization.yaml, system/spegel/namespace.yaml, system/spegel/release.yaml, system/spegel/source.yaml, tests/resources_to_test.txt
=> Spegel deployment elifesciences/issues#9192
